backend:
  name: git-gateway
  branch: master
  identity_url: "https://sandship-theorycraft.netlify.app/.netlify/identity"
  gateway_url: "https://sandship-theorycraft.netlify.app/.netlify/git/github"
media_folder: 'static/img/'
public_folder: 'img'
site_url: https://sandship-theorycraft.netlify.app
display_url: https://sandship-theorycraft.netlify.app
collections:
  - name: builds
    label: Builds
    label_singular: Build
    folder: 'content/build'
    path: '{{slug}}/index'
    identifier_field: identifier
    summary: '{{fields.input}} > {{fields.output}}'
    create: true
    fields:  # The fields each document in this collection have
      - {label: "Identifier", name: "identifier", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Size", name: "size", widget: "string"}
      - label: Input
        name: input
        required: false
        widget: list
        fields:
          - {label: Material, name: material, widget: string}
          - {label: Rate, name: rate, widget: string, required: true}
      - label: Output
        name: output
        required: false
        widget: list
        fields:
          - {label: Material, name: material, widget: string}
          - {label: Rate, name: rate, widget: string, required: true}
          - {label: Reliability, name: reliability, widget: string, required: true}
      - label: "Authors"
        name: "authors"
        required: false
        widget: "list"
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}
